In [23]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd

X, y = load_iris(return_X_y=True, as_frame=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.3)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression(random_state=0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


def print_metrics(y_test, y_pred):
    print('Accuracy: ', accuracy_score(y_test, y_pred))
    print('Confusion Matrix: \n', confusion_matrix(y_test, y_pred))
    print('Classification Report: \n', classification_report(y_test, y_pred))

def print_importance_coef(model, X):
    coef = model.coef_
    coef_names = X.columns
    coef_abs = np.abs(coef)
    coef_max = np.max(coef_abs)
    coef_rel = coef_abs / coef_max
    coef_df = pd.DataFrame(coef_rel, columns=coef_names)
    print('Feature Importance: \n')
    print(coef_df)

print_metrics(y_test, y_pred)
print('\n')
print_importance_coef(model, X)


Accuracy:  0.9777777777777777
Confusion Matrix: 
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45





Feature Importance: 

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.424168          0.438027           0.751203          0.704974
1           0.233986          0.153591           0.114633          0.295026
2           0.190182          0.284436           0.865836          1.000000


In [20]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [16]:
model.coef_

array([[-0.98719189,  1.01944643, -1.74832086, -1.64072949],
       [ 0.54456962, -0.35746202, -0.26679194, -0.68663194],
       [ 0.44262227, -0.66198441,  2.01511281,  2.32736143]])